apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crud-app
  template:
    metadata:
      labels:
        app: crud-app
    spec:
      containers:
        - name: crud-app
          image: my-go-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "db-service"
            - name: CACHE_HOST
              value: "cache-service"
---
apiVersion: v1
kind: Service
metadata:
  name: crud-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: crud-app