apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crud-app
  template:
    metadata:
      labels:
        app: crud-app
    spec:
      containers:
        - name: crud-app
          image: alemkakenuly/my-go-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: db-service
            - name: DB_PORT
              value: "3307"
            - name: DB_NAME
              value: go_db
            - name: DB_USER
              value: go_user
            - name: DB_PASSWORD
              value: "go_password"
---
apiVersion: v1
kind: Service
metadata:
  name: crud-app-service
spec:
  type: LoadBalancer
  selector:
    app: crud-app
  ports:
    - port: 80
      targetPort: 8080