stages:
  - build
  - test

variables:
  GO_VERSION: "1.20"

build:
  stage: build
  image: golang:${GO_VERSION}
  script:
    - go mod tidy
    - go build -o myapp

test:
  stage: test
  image: golang:${GO_VERSION}
  script:
    - go test ./...